"""Enrich roots with detailed descriptions: etymology, core senses and
typical derived words with morpheme breakdowns.

Updates the `description` column of the roots table. Idempotent — safe to
re-run. The short `meaning` stays untouched (it is used for graph labels).

Usage (from backend/):
    python scripts/enrich_roots.py
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import text

from core.database import engine

# root text -> detailed description
# Format: 词源 / 核心义 / 典型词（构词拆解 → 词义）
DETAILED_ROOTS: dict[str, str] = {
    "aer": "词源：希腊语 aēr「空气」\n核心义：空气；航空；气体\n典型词：aerobic ＝ aer(空气)＋bic → 有氧的；aerial ＝ aer(空气)＋ial → 空中的、天线；aeroplane ＝ aero(空气)＋plane → 飞机",
    "agri": "词源：拉丁语 ager「田地」\n核心义：田地；农业；土壤\n典型词：agriculture ＝ agri(田地)＋cult(耕种)＋ure → 农业；agrarian ＝ agr(田地)＋arian → 土地的、农业的",
    "alt": "词源：拉丁语 altus「高的」\n核心义：高；高度；崇高\n典型词：altitude ＝ alt(高)＋itude → 海拔、高度；exalt ＝ ex(出)＋alt(高) → 提升、赞扬；alto ＝ alt(高)＋o → 中音（男声较高音部）",
    "anim": "词源：拉丁语 anima「生命、气息」\n核心义：生命；精神；气息\n典型词：animal ＝ anim(生命)＋al → 动物；unanimous ＝ uni(同一)＋anim(心灵)＋ous → 全体一致的；animate ＝ anim(生命)＋ate → 使有生气",
    "ann": "词源：拉丁语 annus「年」\n核心义：年；一年一度\n典型词：annual ＝ ann(年)＋ual → 每年的；anniversary ＝ ann(年)＋vers(转)＋ary → 周年纪念日；annals ＝ ann(年)＋als → 编年史",
    "apt": "词源：拉丁语 aptus「适合的」\n核心义：适合；适应；倾向\n典型词：adapt ＝ ad(去)＋apt(适合) → 适应；aptitude ＝ apt(适合)＋itude → 天资、才能；apt → 恰当的、易于……的",
    "aqu": "词源：拉丁语 aqua「水」\n核心义：水\n典型词：aquarium ＝ aqu(水)＋arium(场所) → 水族馆；aquatic ＝ aqu(水)＋atic → 水生的；aqueduct ＝ aque(水)＋duct(引导) → 引水渠",
    "arbor": "词源：拉丁语 arbor「树」\n核心义：树；树木\n典型词：arboretum ＝ arbor(树)＋etum(场所) → 树木园；arboreal ＝ arbor(树)＋eal → 树栖的；arborist ＝ arbor(树)＋ist → 树艺师",
    "arm": "词源：拉丁语 arma「武器」\n核心义：武器；武装\n典型词：armor ＝ arm(武器)＋or → 盔甲；armament ＝ arm(武器)＋ament → 军备；disarm ＝ dis(去除)＋arm(武器) → 解除武装；army ＝ arm(武器)＋y → 军队",
    "aud": "词源：拉丁语 audire「听」\n核心义：听；听觉\n典型词：audience ＝ audi(听)＋ence → 听众；audible ＝ audi(听)＋ible(可……的) → 听得见的；auditorium ＝ audit(听)＋orium(场所) → 礼堂、讲堂",
    "avi": "词源：拉丁语 avis「鸟」\n核心义：鸟；飞行\n典型词：aviation ＝ avi(飞行)＋ation → 航空；aviator ＝ avi(飞行)＋ator → 飞行员；aviary ＝ avi(鸟)＋ary(场所) → 鸟舍",
    "bell": "词源：拉丁语 bellum「战争」\n核心义：战争；打斗\n典型词：bellicose ＝ bell(战争)＋icose → 好战的；rebel ＝ re(相反)＋bel(打斗) → 反叛；belligerent ＝ belli(战争)＋ger(带来)＋ent → 交战的",
    "bibli": "词源：希腊语 biblion「书」\n核心义：书；书籍\n典型词：bibliography ＝ biblio(书)＋graph(书写)＋y → 参考书目；bibliophile ＝ biblio(书)＋phil(爱) → 爱书者；Bible ＝ bibl(书)＋e → 圣经",
    "bio": "词源：希腊语 bios「生命」\n核心义：生命；生物\n典型词：biology ＝ bio(生命)＋logy(学科) → 生物学；biography ＝ bio(生命)＋graph(写)＋y → 传记；antibiotic ＝ anti(反对)＋bio(生命)＋tic → 抗生素",
    "bov": "词源：拉丁语 bos / bovis「牛」\n核心义：牛\n典型词：bovine ＝ bov(牛)＋ine → 牛的、牛科的；bovicide ＝ bovi(牛)＋cide(杀) → 杀牛者",
    "brev": "词源：拉丁语 brevis「短的」\n核心义：短；简洁\n典型词：brevity ＝ brev(短)＋ity → 简短；abbreviate ＝ ab(去)＋brev(短)＋iate → 缩写；brief ＝ brev 的变体 → 简短的",
    "calcul": "词源：拉丁语 calculus「石子」（古罗马人用石子计数）\n核心义：计算；石\n典型词：calculate ＝ calcul(计算)＋ate → 计算；calculation ＝ calcul(计算)＋ation → 计算、预料；calculus ＝ calcul(石子)＋us → 微积分、结石",
    "cardi": "词源：希腊语 kardia「心」\n核心义：心脏\n典型词：cardiac ＝ cardi(心)＋ac → 心脏的；cardiology ＝ cardio(心)＋logy(学科) → 心脏病学；cardiogram ＝ cardio(心)＋gram(描绘) → 心电图",
    "ced": "词源：拉丁语 cedere「行走、让与」\n核心义：走；让步；割让\n典型词：proceed ＝ pro(向前)＋ceed(走) → 前进；recede ＝ re(回)＋cede(走) → 后退；concede ＝ con(完全)＋cede(让) → 让步、承认",
    "cess": "词源：拉丁语 cedere 的分词形式（与 ced 同源）\n核心义：走；让与\n典型词：access ＝ ac(去)＋cess(走) → 通道、进入；process ＝ pro(向前)＋cess(走) → 过程；success ＝ suc(下)＋cess(走) → 成功（走下去的结果）",
    "chron": "词源：希腊语 chronos「时间」\n核心义：时间\n典型词：chronic ＝ chron(时间)＋ic → 慢性的（时间长的）；chronicle ＝ chron(时间)＋icle → 编年史；synchronize ＝ syn(共同)＋chron(时间)＋ize → 同步",
    "cid": "词源：拉丁语 cadere「落下」\n核心义：落；降临；偶然发生\n典型词：incident ＝ in(上)＋cid(落)＋ent → 事件（落到头上的事）；accident ＝ ac(去)＋cid(落)＋ent → 事故；coincide ＝ co(共同)＋in(上)＋cide(落) → 同时发生",
    "cis": "词源：拉丁语 caedere「切」\n核心义：切；割\n典型词：decide ＝ de(断)＋cide(切) → 决定（切断犹豫）；concise ＝ con(完全)＋cise(切) → 简明的（切到不留多余）；incisive ＝ in(入)＋cis(切)＋ive → 尖锐深刻的",
    "civ": "词源：拉丁语 civis「公民」\n核心义：公民；城市\n典型词：citizen ＝ civit(公民)的变体 → 市民；civil ＝ civ(公民)＋il → 公民的、国内的；civilization ＝ civ(公民)＋il＋iz＋ation → 文明",
    "clar": "词源：拉丁语 clarus「明亮的、清楚的」\n核心义：清楚；明亮；著名\n典型词：clarify ＝ clar(清楚)＋ify(使……) → 澄清；declare ＝ de(加强)＋clare(清楚) → 宣布、声明；clarity ＝ clar(清楚)＋ity → 清晰",
    "class": "词源：拉丁语 classis「等级、类别」\n核心义：等级；类别；班级\n典型词：classify ＝ class(类别)＋ify(使……) → 分类；classic ＝ class(等级)＋ic → 经典的；classical ＝ class(等级)＋ical → 古典的",
    "clos": "词源：拉丁语 claudere「关闭」（clos 为其变体）\n核心义：关闭\n典型词：closet ＝ clos(关闭)＋et → 壁橱、私室；disclose ＝ dis(打开)＋close(关) → 揭露；enclosure ＝ en(入)＋clos(关)＋ure → 围场、附件",
    "clud": "词源：拉丁语 claudere「关闭」\n核心义：关闭；包含\n典型词：include ＝ in(入)＋clude(关) → 包含；exclude ＝ ex(出)＋clude(关) → 排除；conclude ＝ con(完全)＋clude(关) → 结束、下结论",
    "clus": "词源：拉丁语 claudere 的分词词干（与 clud 同源）\n核心义：关闭\n典型词：conclusion ＝ con(完全)＋clus(关)＋ion → 结论；exclusion ＝ ex(出)＋clus(关)＋ion → 排斥；seclusion ＝ se(分离)＋clus(关)＋ion → 隐居",
    "cogn": "词源：拉丁语 cognoscere「知道」\n核心义：知道；认识\n典型词：cognition ＝ cogn(知道)＋ition → 认知；recognize ＝ re(再)＋cogn(认识)＋ize → 认出；cognitive ＝ cogn(知道)＋itive → 认知的",
    "cord": "词源：拉丁语 cor「心」\n核心义：心；心脏；心意\n典型词：cordial ＝ cord(心)＋ial → 热诚的；accord ＝ ac(去)＋cord(心) → 一致（心往一处）；discord ＝ dis(分离)＋cord(心) → 不和；concord ＝ con(共同)＋cord(心) → 和谐",
    "corp": "词源：拉丁语 corpus「身体」\n核心义：身体；团体\n典型词：corps ＝ corp(身体)＋s → 军团；corpse ＝ corp(身体)＋se → 尸体；incorporate ＝ in(入)＋corpor(身体)＋ate → 合并、纳入；corporation ＝ corpor(团体)＋ation → 公司",
    "cover": "词源：拉丁语 cooperire「盖住」\n核心义：覆盖；掩护\n典型词：cover ＝ cover(盖) → 覆盖、封面；discover ＝ dis(去除)＋cover(盖) → 发现；recover ＝ re(重新)＋cover(盖) → 恢复、找回",
    "creat": "词源：拉丁语 creare「创造」\n核心义：创造；产生\n典型词：create ＝ creat(创造)＋e → 创造；creative ＝ creat(创造)＋ive → 有创造力的；creature ＝ creat(造)＋ure → 生物、造物；recreation ＝ re(再)＋creat(创造)＋ion → 娱乐、消遣",
    "cred": "词源：拉丁语 credere「相信」\n核心义：相信；信任；信用\n典型词：credit ＝ cred(相信)＋it → 信用、学分；credible ＝ cred(相信)＋ible(可……的) → 可信的；incredible ＝ in(不)＋cred(信)＋ible → 难以置信的；credential ＝ cred(信)＋ential → 证书、资历",
    "crim": "词源：拉丁语 crimen「罪行」\n核心义：罪行；控诉\n典型词：crime ＝ crim(罪)＋e → 罪行；criminal ＝ crimin(罪)＋al → 罪犯；criminology ＝ crimin(罪)＋ology(学科) → 犯罪学；discriminate ＝ dis(分离)＋crimin(辨别)＋ate → 歧视、区别",
    "cry": "词源：希腊语 kryos「冰冻」\n核心义：冷；冰冻；隐藏\n典型词：crystal ＝ cry(冷)＋stal → 水晶（清澈如冰）；cryogenic ＝ cryo(冷)＋genic → 低温的；crypt ＝ cry(隐藏)＋pt → 地窖（与「隐藏」义相关）",
    "culp": "词源：拉丁语 culpa「过错」\n核心义：过错；罪责\n典型词：culprit ＝ culp(罪)＋prit → 罪犯；culpable ＝ culp(过错)＋able → 应受谴责的；exculpate ＝ ex(出)＋culp(罪)＋ate → 开脱（使罪责脱身）",
    "cult": "词源：拉丁语 colere「耕种、培养」\n核心义：耕种；培养；崇拜\n典型词：cultivate ＝ cult(培养)＋ivate → 培养、耕作；culture ＝ cult(培养)＋ure → 文化；agriculture ＝ agri(田)＋cult(耕)＋ure → 农业",
    "curs": "词源：拉丁语 currere「跑」\n核心义：跑；流动\n典型词：cursor ＝ curs(跑)＋or → 光标（跑动之物）；excursion ＝ ex(出)＋curs(跑)＋ion → 远足；precursor ＝ pre(前)＋curs(跑)＋or → 先驱；cursive ＝ curs(跑)＋ive → 草书的（连笔如流水）",
    "dem": "词源：希腊语 dēmos「人民」\n核心义：人民；民众\n典型词：democracy ＝ demo(人民)＋cracy(统治) → 民主；epidemic ＝ epi(在……之中)＋dem(民众)＋ic → 流行病（在民众中）；demographics ＝ demo(民众)＋graph(描绘)＋ics → 人口统计学",
    "dent": "词源：拉丁语 dens「牙齿」\n核心义：牙齿\n典型词：dentist ＝ dent(牙)＋ist → 牙医；dental ＝ dent(牙)＋al → 牙齿的；trident ＝ tri(三)＋dent(齿) → 三叉戟；indent ＝ in(成)＋dent(齿状) → 缩进",
    "derm": "词源：希腊语 derma「皮肤」\n核心义：皮肤\n典型词：dermatology ＝ derma(皮肤)＋logy(学科) → 皮肤病学；hypodermic ＝ hypo(下)＋derm(皮肤)＋ic → 皮下的（注射）；epidermis ＝ epi(上)＋derm(皮)＋is → 表皮",
    "dict": "词源：拉丁语 dicere「说」\n核心义：说；讲；言辞\n典型词：dictionary ＝ dict(说)＋ion＋ary → 词典（说话的工具）；predict ＝ pre(预先)＋dict(说) → 预言；verdict ＝ ver(真实)＋dict(说) → 裁决；dictate ＝ dict(说)＋ate → 口述、命令",
    "disc": "词源：拉丁语 discere「学习」\n核心义：学习；学科\n典型词：discipline ＝ disc(学)＋ipline → 纪律、学科；disciple ＝ disc(学)＋iple → 门徒、弟子",
    "diurn": "词源：拉丁语 diurnus「每日的」（来自 dies「日」）\n核心义：日；白天\n典型词：diary ＝ di(日)＋ary → 日记；journal ＝ journ(日)＋al → 日报、日志；diurnal ＝ diurn(日)＋al → 白昼的",
    "divid": "词源：拉丁语 dividere「分开」\n核心义：分开；分配\n典型词：divide ＝ divid(分)＋e → 分开；dividend ＝ divid(分)＋end → 股息（分配所得）；individual ＝ in(不)＋divid(分)＋ual → 个体（不可再分）",
    "divis": "词源：拉丁语 dividere 的分词词干（与 divid 同源）\n核心义：分开；分割\n典型词：division ＝ divis(分)＋ion → 部门、除法；divisor ＝ divis(分)＋or → 除数；subdivision ＝ sub(下)＋divis(分)＋ion → 细分",
    "doc": "词源：拉丁语 docere「教导」\n核心义：教导；教授\n典型词：doctor ＝ doc(教导)＋tor → 博士、医生（原指学者）；document ＝ doc(教导)＋ument → 文件（用以说明之物）；doctrine ＝ doctr(教导)＋ine → 学说、教义",
    "don": "词源：拉丁语 donare「赠送」\n核心义：给予；捐赠\n典型词：donate ＝ don(给)＋ate → 捐赠；donor ＝ don(给)＋or → 捐赠者；pardon ＝ par(完全)＋don(给) → 原谅（完全给予宽恕）",
    "dot": "词源：拉丁语 dotare「赋予」（与 don 同源，来自 dos「给予之物」）\n核心义：给予；天赋\n典型词：dot ＝ dot(给) → 嫁妆；endow ＝ en(使)＋dow(给) → 赋予、捐赠；anecdote ＝ an(不)＋ec(出)＋dot(给)＋e → 轶事（未公开发表之物）",
    "duc": "词源：拉丁语 ducere「引导」\n核心义：引导；带领\n典型词：educate ＝ e(出)＋duc(引导)＋ate → 教育（引导出潜能）；introduce ＝ intro(向内)＋duce(引) → 介绍；reduce ＝ re(回)＋duce(引) → 减少、降低",
    "duct": "词源：拉丁语 ducere 的分词词干（与 duc 同源）\n核心义：引导；导管\n典型词：conduct ＝ con(共同)＋duct(引) → 引导、指挥；product ＝ pro(向前)＋duct(引) → 产品（引导出来的东西）；aqueduct ＝ aque(水)＋duct(引) → 引水渠",
    "dur": "词源：拉丁语 durus「硬的」\n核心义：硬；持久；耐久\n典型词：durable ＝ dur(持久)＋able → 耐用的；duration ＝ dur(持续)＋ation → 持续时间；endure ＝ en(使)＋dure(持久) → 忍耐、持续；obdurate ＝ ob(对抗)＋dur(硬)＋ate → 顽固的",
    "enni": "词源：拉丁语 annus「年」的变体\n核心义：年\n典型词：biennial ＝ bi(两)＋enni(年)＋al → 两年一次的；perennial ＝ per(贯穿)＋enni(年)＋al → 终年的、长久的；centennial ＝ cent(百)＋enni(年)＋al → 百年纪念",
    "equ": "词源：拉丁语 aequus「相等的」\n核心义：相等；平等；马\n典型词：equal ＝ equ(相等)＋al → 相等的；equator ＝ equat(相等)＋or → 赤道（平分昼夜）；equilibrium ＝ equi(相等)＋libr(平衡)＋ium → 平衡；adequate ＝ ad(去)＋equ(相等)＋ate → 足够的",
    "erg": "词源：希腊语 ergon「工作」\n核心义：工作；能量\n典型词：energy ＝ en(在……中)＋erg(工作)＋y → 能量；ergonomic ＝ ergo(工作)＋nom(法则)＋ic → 人机工程学的；synergistic ＝ syn(共同)＋erg(工作)＋istic → 协同的",
    "ethn": "词源：希腊语 ethnos「民族」\n核心义：民族；种族\n典型词：ethnic ＝ ethn(民族)＋ic → 民族的；ethnography ＝ ethno(民族)＋graph(描绘)＋y → 民族志；ethnocentric ＝ ethno(民族)＋centr(中心)＋ic → 民族中心主义的",
    "fac": "词源：拉丁语 facere「做」\n核心义：做；制造\n典型词：factory ＝ fact(做)＋ory(场所) → 工厂；facile ＝ fac(做)＋ile → 轻易的；facilitate ＝ facil(容易)＋itate → 使容易、促进",
    "fact": "词源：拉丁语 facere 的分词词干（与 fac 同源）\n核心义：做；事实\n典型词：fact ＝ fact(做) → 事实（已做成的事）；manufacture ＝ manu(手)＋fact(做)＋ure → 制造；factor ＝ fact(做)＋or → 因素；perfect ＝ per(完全)＋fect(做) → 完美的",
    "fect": "词源：拉丁语 facere 的变体词干（与 fac 同源）\n核心义：做；作用\n典型词：affect ＝ af(去)＋fect(做) → 影响；effect ＝ ef(出)＋fect(做) → 效果；infect ＝ in(入)＋fect(做) → 感染；efficient ＝ ef(出)＋fic(做)＋ient → 高效的",
    "feder": "词源：拉丁语 foedus「联盟、条约」\n核心义：联盟；联合\n典型词：federal ＝ feder(联盟)＋al → 联邦的；federation ＝ feder(联盟)＋ation → 联邦、联合会；confederate ＝ con(共同)＋feder(联盟)＋ate → 同盟的",
    "fer": "词源：拉丁语 ferre「带来、承载」\n核心义：带来；运送；承受\n典型词：transfer ＝ trans(转移)＋fer(带) → 转移；prefer ＝ pre(前)＋fer(拿) → 更喜欢（先拿）；offer ＝ of(向)＋fer(给) → 提供；differ ＝ dif(分开)＋fer(带) → 不同",
    "fic": "词源：拉丁语 facere 的变体词干（与 fac 同源）\n核心义：做\n典型词：efficient ＝ ef(出)＋fic(做)＋ient → 高效的；sufficient ＝ suf(下)＋fic(做)＋ient → 足够的；deficient ＝ de(离)＋fic(做)＋ient → 不足的；proficient ＝ pro(前)＋fic(做)＋ient → 精通的",
    "fid": "词源：拉丁语 fides「信任、忠诚」\n核心义：信任；忠诚\n典型词：fidelity ＝ fid(信任)＋elity → 忠实；confide ＝ con(完全)＋fide(信任) → 吐露、信赖；infidelity ＝ in(不)＋fidel(忠)＋ity → 不忠；confident ＝ con(完全)＋fid(信)＋ent → 自信的",
    "fig": "词源：拉丁语 fingere「塑造、虚构」\n核心义：塑造；形状；虚构\n典型词：figure ＝ fig(形状)＋ure → 形象、数字；configure ＝ con(完全)＋fig(塑形)＋ure → 配置；fictitious ＝ fict(虚构)＋itious → 虚构的；fiction ＝ fict(塑造)＋ion → 小说",
    "fin": "词源：拉丁语 finis「界限、结束」\n核心义：界限；结束\n典型词：final ＝ fin(结束)＋al → 最后的；define ＝ de(下)＋fine(界限) → 下定义；infinite ＝ in(无)＋fin(界限)＋ite → 无限的；refine ＝ re(再)＋fine(界限) → 精炼",
    "firm": "词源：拉丁语 firmus「坚固的」\n核心义：坚固；坚定\n典型词：firm ＝ firm(坚固) → 坚固的、公司；confirm ＝ con(完全)＋firm(坚固) → 确认；affirm ＝ af(去)＋firm(坚定) → 肯定、断言；infirmity ＝ in(不)＋firm(坚固)＋ity → 虚弱",
    "flect": "词源：拉丁语 flectere「使弯曲」\n核心义：弯曲；折\n典型词：reflect ＝ re(回)＋flect(弯) → 反射、反思；flexible ＝ flex(弯)＋ible(可……的) → 灵活的；deflect ＝ de(离)＋flect(弯) → 使偏斜；inflection ＝ in(向)＋flect(弯)＋ion → 变调、屈折",
    "flex": "词源：拉丁语 flectere 的变体（与 flect 同源）\n核心义：弯曲\n典型词：flex ＝ flex(弯) → 弯曲；flexible ＝ flex(弯)＋ible → 柔韧的、灵活的；reflex ＝ re(回)＋flex(弯) → 反射、本能反应",
    "flor": "词源：拉丁语 flos「花」\n核心义：花；开花\n典型词：floral ＝ flor(花)＋al → 花的；flourish ＝ flour(花)＋ish → 繁荣（如花盛开）；florist ＝ flor(花)＋ist → 花商；florid ＝ flor(花)＋id → 绚丽的",
    "flu": "词源：拉丁语 fluere「流动」\n核心义：流；流动\n典型词：fluent ＝ flu(流)＋ent → 流利的；influence ＝ in(入)＋flu(流)＋ence → 影响（流入之物）；fluid ＝ flu(流)＋id → 流体；influenza ＝ influ(流入)＋enza → 流感",
    "flux": "词源：拉丁语 fluxus「流动」（fluere 的分词）\n核心义：流；涌；变迁\n典型词：flux ＝ flux(流) → 流动、变迁；influx ＝ in(入)＋flux(流) → 涌入；reflux ＝ re(回)＋flux(流) → 逆流、反流",
    "foli": "词源：拉丁语 folium「叶子」\n核心义：叶\n典型词：foliage ＝ foli(叶)＋age → 树叶；portfolio ＝ port(携带)＋folio(叶/纸) → 公文包、作品集；trifoliate ＝ tri(三)＋foli(叶)＋ate → 三叶的",
    "form": "词源：拉丁语 forma「形状、形式」\n核心义：形状；形式；形成\n典型词：formal ＝ form(形式)＋al → 正式的；formation ＝ form(形)＋ation → 形成；reform ＝ re(再)＋form(形) → 改革；transform ＝ trans(转换)＋form(形) → 变形、转变",
    "found": "词源：拉丁语 fundus「底部、基础」\n核心义：底部；基础；铸造\n典型词：foundation ＝ found(底)＋ation → 基础、基金会；profound ＝ pro(前/深)＋found(底) → 深刻的；fundamental ＝ fund(基础)＋a＋mental → 基本的",
    "fract": "词源：拉丁语 frangere「打碎」\n核心义：破裂；折断\n典型词：fracture ＝ fract(破)＋ure → 骨折、断裂；fraction ＝ fract(破)＋ion → 分数、部分；refraction ＝ re(回)＋fract(折)＋ion → 折射",
    "frag": "词源：拉丁语 frangere 的变体（与 fract 同源）\n核心义：碎；易碎\n典型词：fragile ＝ frag(碎)＋ile(易……的) → 易碎的；fragment ＝ frag(碎)＋ment → 碎片；suffrage ＝ suf(下)＋frage(碎裂→意见碎片) → 投票",
    "fug": "词源：拉丁语 fugere「逃跑」\n核心义：逃跑；逃避\n典型词：refugee ＝ re(回)＋fug(逃)＋ee → 难民；fugitive ＝ fug(逃)＋itive → 逃亡者；centrifugal ＝ centri(中心)＋fug(逃)＋al → 离心的",
    "fund": "词源：拉丁语 fundere「倾倒、熔铸」\n核心义：倾倒；熔铸；注入\n典型词：foundry ＝ found(铸)＋ry → 铸造厂；confound ＝ con(一起)＋found(倒) → 使混淆；refund ＝ re(回)＋fund(倒) → 退款",
    "fus": "词源：拉丁语 fundere 的分词词干（与 fund 同源）\n核心义：倾倒；熔合\n典型词：confuse ＝ con(一起)＋fuse(倒) → 使混乱；refuse ＝ re(回)＋fuse(倒) → 拒绝（倒回去）；diffuse ＝ dif(分开)＋fuse(倒) → 扩散的；fusion ＝ fus(熔)＋ion → 熔合、聚变",
    "gen": "词源：拉丁语 gens「氏族、出生」/希腊语 genos「种类」\n核心义：出生；产生；种类\n典型词：generate ＝ gen(产生)＋erate → 产生；genetic ＝ gen(出生)＋etic → 遗传的；generous ＝ gener(出生→贵族出身)＋ous → 慷慨的；gentle ＝ gent(出身好)＋le → 温和的",
    "gener": "词源：拉丁语 genus「种类」（gen 的扩展形式）\n核心义：产生；种类；一代\n典型词：generation ＝ gener(产生)＋ation → 一代人；degenerate ＝ de(向下)＋gener(产生)＋ate → 退化；regenerate ＝ re(再)＋gener(产生)＋ate → 再生；generic ＝ gener(种类)＋ic → 通用的",
    "geo": "词源：希腊语 gē「地球」\n核心义：地球；土地\n典型词：geography ＝ geo(地)＋graph(描绘)＋y → 地理；geology ＝ geo(地)＋logy(学科) → 地质学；geometry ＝ geo(地)＋metry(测量) → 几何（原为测地术）",
    "ger": "词源：拉丁语 gerere「搬运、进行」\n核心义：搬运；进行；实施\n典型词：belligerent ＝ belli(战争)＋ger(进行)＋ent → 交战的；gesture ＝ gest(搬运→表达)＋ure → 手势；digest ＝ di(分开)＋gest(运) → 消化、摘要",
    "gnor": "词源：拉丁语 ignorare「不知道」\n核心义：不知道；忽视\n典型词：ignorant ＝ ignor(不知)＋ant → 无知的；ignore ＝ ignor(不知)＋e → 忽视；ignoramus ＝ ignor(不知)＋amus → 无知者",
    "graci": "词源：拉丁语 gratia「恩惠、优雅」\n核心义：优雅；恩惠；感激\n典型词：grace ＝ grac(优雅)＋e → 优雅；gracious ＝ graci(优雅)＋ous → 和蔼的；ingratiate ＝ in(入)＋grati(恩惠)＋ate → 讨好",
    "grad": "词源：拉丁语 gradus「步、级」\n核心义：步；级；行走\n典型词：grade ＝ grad(级)＋e → 年级；gradual ＝ grad(步)＋ual → 逐渐的（一步步）；graduate ＝ grad(级)＋uate → 毕业（完成一级）；upgrade ＝ up(上)＋grade(级) → 升级",
    "gram": "词源：希腊语 gramma「书写之物」\n核心义：书写；文字；克\n典型词：grammar ＝ gram(文字)＋mar → 语法；program ＝ pro(前)＋gram(写) → 节目、程序；telegram ＝ tele(远)＋gram(写) → 电报；diagram ＝ dia(穿过)＋gram(画) → 图表",
    "grand": "词源：拉丁语 grandis「大的」\n核心义：大；宏大；宏伟\n典型词：grand ＝ grand(大) → 宏大的；grandparent ＝ grand(大→隔代)＋parent → 祖父母；grandeur ＝ grand(大)＋eur → 壮丽；aggrandize ＝ ag(去)＋grand(大)＋ize → 扩大",
    "graph": "词源：希腊语 graphein「书写」\n核心义：写；画；记录\n典型词：autograph ＝ auto(自己)＋graph(写) → 亲笔签名；photograph ＝ photo(光)＋graph(画) → 照片；biography ＝ bio(生命)＋graph(写)＋y → 传记；paragraph ＝ para(旁)＋graph(写) → 段落",
    "grat": "词源：拉丁语 gratus「感激的、令人愉悦的」\n核心义：感激；喜悦；恩惠\n典型词：grateful ＝ grat(感激)＋eful → 感激的；gratitude ＝ grat(感激)＋itude → 感谢；gratify ＝ grat(喜悦)＋ify(使……) → 使满意；gratuity ＝ grat(恩惠)＋uity → 小费",
    "greg": "词源：拉丁语 grex「群」\n核心义：群；聚集\n典型词：gregarious ＝ greg(群)＋arious → 爱社交的；aggregate ＝ ag(去)＋greg(聚)＋ate → 聚集、总计；segregate ＝ se(分离)＋greg(群)＋ate → 隔离",
    "gress": "词源：拉丁语 gradi「行走」（grad 的动词词干）\n核心义：行走；前进\n典型词：progress ＝ pro(向前)＋gress(走) → 进步；congress ＝ con(共同)＋gress(走) → 国会（走到一起）；aggressive ＝ ag(去)＋gress(走)＋ive → 侵略的；regress ＝ re(回)＋gress(走) → 倒退",
    "hab": "词源：拉丁语 habere「拥有、持有」\n核心义：拥有；持有；居住\n典型词：habit ＝ hab(持有)＋it → 习惯（持续持有的行为）；inhabit ＝ in(内)＋habit(持有) → 居住于；exhibit ＝ ex(出)＋hibit(持有) → 展出；prohibit ＝ pro(前)＋hibit(持) → 禁止",
    "her": "词源：拉丁语 haerere「粘附」\n核心义：粘附；依附\n典型词：adhere ＝ ad(去)＋here(粘) → 粘附、坚持；coherent ＝ co(共同)＋her(粘)＋ent → 连贯的；inherent ＝ in(内)＋her(粘)＋ent → 固有的",
    "hipp": "词源：希腊语 hippos「马」\n核心义：马\n典型词：hippopotamus ＝ hippo(马)＋potam(河)＋us → 河马（河中之马）；hippology ＝ hippo(马)＋logy(学) → 马学",
    "hydr": "词源：希腊语 hydōr「水」\n核心义：水\n典型词：hydrate ＝ hydr(水)＋ate → 水合物；hydraulic ＝ hydrau(水)＋lic → 液压的；dehydrate ＝ de(去除)＋hydr(水)＋ate → 脱水；carbohydrate ＝ carbo(碳)＋hydr(水)＋ate → 碳水化合物",
    "ign": "词源：拉丁语 ignis「火」\n核心义：火；点燃\n典型词：ignite ＝ ign(火)＋ite → 点燃；igneous ＝ ign(火)＋eous → 火成的（岩石）；ignition ＝ ign(火)＋ition → 点火、点火装置",
    "ject": "词源：拉丁语 jacere「扔、投掷」\n核心义：扔；投；掷\n典型词：inject ＝ in(入)＋ject(扔) → 注射；reject ＝ re(回)＋ject(扔) → 拒绝（扔回去）；project ＝ pro(向前)＋ject(扔) → 投射、项目；eject ＝ e(出)＋ject(扔) → 弹出",
    "join": "词源：拉丁语 jungere「连接」（经由法语 joindre）\n核心义：连接；结合\n典型词：join ＝ join(连) → 加入；joint ＝ join(连)＋t → 关节、联合的；adjoin ＝ ad(去)＋join(连) → 毗邻；conjoin ＝ con(共同)＋join(连) → 结合",
    "jud": "词源：拉丁语 judex「法官」/judicare「判断」\n核心义：判断；审判\n典型词：judge ＝ jud(判断)＋ge → 法官；judgment ＝ judg(判断)＋ment → 判断力；prejudice ＝ pre(预先)＋jud(判断)＋ice → 偏见（先入为主的判断）",
    "judic": "词源：拉丁语 judicare「判断」（jud 的扩展词干）\n核心义：判断；司法\n典型词：judicial ＝ judic(判断)＋ial → 司法的；judiciary ＝ judic(司法)＋iary → 司法部门；adjudicate ＝ ad(去)＋judic(判断)＋ate → 裁决",
    "junct": "词源：拉丁语 jungere 的分词词干（与 join 同源）\n核心义：连接；接合\n典型词：junction ＝ junct(连)＋ion → 交叉点；conjunction ＝ con(共同)＋junct(连)＋ion → 连词、结合；adjunct ＝ ad(去)＋junct(连) → 附属物、助手",
    "jur": "词源：拉丁语 jus/juris「法律」\n核心义：法律；发誓；公正\n典型词：jury ＝ jur(发誓)＋y → 陪审团（宣誓之人）；justice ＝ just(公正)＋ice → 正义；perjury ＝ per(假)＋jur(誓)＋y → 伪证",
    "just": "词源：拉丁语 justus「公正的」（来自 jus「法」）\n核心义：正义；公正；恰当\n典型词：justice ＝ just(公正)＋ice → 正义、司法；justify ＝ just(公正)＋ify(使……) → 证明……合理；adjust ＝ ad(去)＋just(恰当) → 调整；injustice ＝ in(不)＋justice → 不公正",
    "juven": "词源：拉丁语 juvenis「年轻的」\n核心义：年轻；少年\n典型词：juvenile ＝ juven(年轻)＋ile → 青少年的；rejuvenate ＝ re(再)＋juven(年轻)＋ate → 使年轻；juvenilia ＝ juven(少年)＋ilia → 少年作品",
    "labor": "词源：拉丁语 labor「劳动」\n核心义：劳动；工作\n典型词：labor ＝ labor(劳动) → 劳动；laboratory ＝ labor(工作)＋atory(场所) → 实验室；collaborate ＝ col(共同)＋labor(劳动)＋ate → 合作；laborious ＝ labor(劳)＋ious → 费力的",
    "lax": "词源：拉丁语 laxus「松的」\n核心义：松；松弛\n典型词：relax ＝ re(回)＋lax(松) → 放松；laxative ＝ lax(松)＋ative → 缓泻的；laxity ＝ lax(松)＋ity → 松弛、放纵",
    "legis": "词源：拉丁语 lex/legis「法律」\n核心义：法律；立法\n典型词：legislate ＝ legis(法)＋late(带来) → 立法；legislature ＝ legislat(立法)＋ure → 立法机关；legitimate ＝ legitim(合法)＋ate → 合法的；privilege ＝ privi(私人)＋lege(法) → 特权（适用于个人的法）",
    "lingu": "词源：拉丁语 lingua「舌头、语言」\n核心义：语言；舌头\n典型词：language ＝ langu(语言)＋age → 语言；linguistics ＝ lingu(语言)＋istics → 语言学；bilingual ＝ bi(双)＋lingu(语言)＋al → 双语的",
    "liter": "词源：拉丁语 littera「字母」\n核心义：文字；字母；文学\n典型词：literature ＝ liter(文字)＋ature → 文学；literate ＝ liter(文字)＋ate → 识字的；literary ＝ liter(文学)＋ary → 文学的；obliterate ＝ ob(去除)＋liter(字母)＋ate → 涂抹、删除",
    "lith": "词源：希腊语 lithos「石头」\n核心义：石\n典型词：lithograph ＝ litho(石)＋graph(画) → 石版画；monolith ＝ mono(单一)＋lith(石) → 巨石；lithosphere ＝ litho(石)＋sphere(球) → 岩石圈",
    "log": "词源：希腊语 logos「言语、理性、学科」\n核心义：言语；学科；逻辑\n典型词：dialogue ＝ dia(之间)＋log(言)＋ue → 对话；logic ＝ log(理性)＋ic → 逻辑；biology ＝ bio(生命)＋logy(学科) → 生物学；apology ＝ apo(离开)＋logy(说) → 道歉（辩解之辞）",
    "long": "词源：拉丁语 longus「长的」\n核心义：长；长久\n典型词：longitude ＝ long(长)＋itude → 经度；prolong ＝ pro(向前)＋long(长) → 延长；longevity ＝ long(长)＋ev(年龄)＋ity → 长寿；elongate ＝ e(使)＋long(长)＋ate → 拉长",
    "loqu": "词源：拉丁语 loqui「说话」\n核心义：说；言谈\n典型词：eloquent ＝ e(出)＋loqu(说)＋ent → 雄辩的；loquacious ＝ loqu(说)＋acious(多……的) → 多话的；soliloquy ＝ soli(独自)＋loqu(说)＋y → 独白",
    "luc": "词源：拉丁语 lux/lucere「光」\n核心义：光；明亮\n典型词：lucid ＝ luc(光)＋id → 清晰的；translucent ＝ trans(穿过)＋luc(光)＋ent → 半透明的；elucidate ＝ e(出)＋lucid(明)＋ate → 阐明",
    "lud": "词源：拉丁语 ludere「玩耍」\n核心义：玩耍；表演\n典型词：ludicrous ＝ lud(玩)＋icrous → 荒谬可笑的；illusion ＝ il(入)＋lus(玩)＋ion → 幻觉（把玩的假象）；allusion ＝ al(去)＋lus(玩→暗指)＋ion → 暗指",
    "lumin": "词源：拉丁语 lumen「光」\n核心义：光；发光\n典型词：luminous ＝ lumin(光)＋ous → 发光的；illuminate ＝ il(入)＋lumin(光)＋ate → 照亮；luminary ＝ lumin(光)＋ary → 杰出人物（发光体）",
    "lun": "词源：拉丁语 luna「月亮」\n核心义：月亮\n典型词：lunar ＝ lun(月)＋ar → 月亮的；lunatic ＝ lunat(月)＋ic → 疯的（古时认为受月光影响）；semilunar ＝ semi(半)＋lun(月)＋ar → 半月形的",
    "magn": "词源：拉丁语 magnus「大的」\n核心义：大；巨大\n典型词：magnify ＝ magn(大)＋ify(使……) → 放大；magnitude ＝ magn(大)＋itude → 巨大、震级；magnificent ＝ magn(大)＋fic(做)＋ent → 壮丽的",
    "maj": "词源：拉丁语 major「较大的」（magnus 的比较级）\n核心义：较大；主要\n典型词：major ＝ maj(大)＋or → 主要的、专业；majority ＝ major(较大)＋ity → 大多数；mayor ＝ maj(大)＋or → 市长（原指首领）",
    "man": "词源：拉丁语 manus「手」\n核心义：手；手工；管理\n典型词：manual ＝ manu(手)＋al → 手工的、手册；manufacture ＝ manu(手)＋fact(做)＋ure → 制造；manuscript ＝ manu(手)＋script(写) → 手稿；manage ＝ man(手)＋age → 管理（用手处理）",
    "mar": "词源：拉丁语 mare「海」\n核心义：海；海洋\n典型词：marine ＝ mar(海)＋ine → 海洋的；submarine ＝ sub(下)＋mar(海)＋ine → 潜艇；maritime ＝ marit(海)＋ime → 海事的；mariner ＝ marin(海)＋er → 水手",
    "math": "词源：希腊语 mathēma「学习、知识」\n核心义：学习；知识\n典型词：mathematics ＝ mathemat(学习)＋ics → 数学；polymath ＝ poly(多)＋math(学) → 博学者；mathematician ＝ mathemat(数学)＋ician → 数学家",
    "meas": "词源：拉丁语 mensura「测量」（metiri 的名词）\n核心义：测量；尺寸\n典型词：measure ＝ meas(测)＋ure → 测量；dimension ＝ di(分开)＋mens(测)＋ion → 尺寸、维度；immense ＝ im(无)＋mense(测) → 巨大的（无法测量的）",
    "medic": "词源：拉丁语 medicus「医生」/mederi「治疗」\n核心义：治疗；医生\n典型词：medicine ＝ medic(治疗)＋ine → 医学、药；medical ＝ medic(医)＋al → 医疗的；remedy ＝ re(再)＋med(治疗)＋y → 药物、补救",
    "memor": "词源：拉丁语 memoria「记忆」\n核心义：记忆；纪念\n典型词：memory ＝ memor(记忆)＋y → 记忆；memorial ＝ memor(记)＋ial → 纪念碑；remember ＝ re(再)＋member(记忆) → 记得；commemorate ＝ com(共同)＋memor(记)＋ate → 纪念",
    "merc": "词源：拉丁语 mercari「贸易」/merx「商品」\n核心义：贸易；商品；报酬\n典型词：merchant ＝ merch(贸易)＋ant → 商人；commerce ＝ com(共同)＋merc(贸易)＋e → 商业；market ＝ mark(merc 的变体)＋et → 市场；mercenary ＝ mercen(报酬)＋ary → 唯利是图的",
    "meter": "词源：希腊语 metron「测量」\n核心义：测量；计量\n典型词：thermometer ＝ thermo(热)＋meter(计) → 温度计；diameter ＝ dia(穿过)＋meter(测) → 直径；symmetry ＝ sym(共同)＋metry(测量) → 对称；meter ＝ meter(计量) → 米、仪表",
    "micro": "词源：希腊语 mikros「小的」\n核心义：小；微\n典型词：microscope ＝ micro(微)＋scope(观察) → 显微镜；microwave ＝ micro(微)＋wave(波) → 微波；microbe ＝ micro(微)＋be(bios 生命) → 微生物",
    "migr": "词源：拉丁语 migrare「迁移」\n核心义：迁移；移居\n典型词：migrate ＝ migr(迁)＋ate → 迁移；immigrant ＝ im(入)＋migr(迁)＋ant → （外来）移民；emigrant ＝ e(出)＋migr(迁)＋ant → （移出）移民",
    "milit": "词源：拉丁语 miles「士兵」\n核心义：士兵；战斗\n典型词：military ＝ milit(士兵)＋ary → 军事的；militant ＝ milit(战斗)＋ant → 激进的；militia ＝ milit(兵)＋ia → 民兵",
    "mini": "词源：拉丁语 minimus「最小的」\n核心义：小；微小\n典型词：minimum ＝ minim(最小)＋um → 最小值；miniature ＝ mini(小)＋ature → 微型画（原指小红书上的细密画）；diminish ＝ di(使)＋minish(小) → 减少；minor ＝ min(小)＋or → 较小的",
    "miss": "词源：拉丁语 mittere「送」的分词词干\n核心义：送；派出；释放\n典型词：mission ＝ miss(送)＋ion → 任务（被派出之事）；transmission ＝ trans(转移)＋miss(送)＋ion → 传输；permission ＝ per(通过)＋miss(送)＋ion → 许可",
    "mit": "词源：拉丁语 mittere「送、派出」\n核心义：送；派；扔\n典型词：transmit ＝ trans(转移)＋mit(送) → 传输；permit ＝ per(通过)＋mit(送) → 允许；dismiss ＝ dis(分开)＋miss(送) → 解散、解雇；submit ＝ sub(下)＋mit(送) → 提交",
    "mob": "词源：拉丁语 movere「移动」（mobile 的词干）\n核心义：移动；动\n典型词：mobile ＝ mob(动)＋ile → 移动的；automobile ＝ auto(自己)＋mob(动)＋ile → 汽车；mobilize ＝ mob(动)＋ilize → 动员；mob ＝ mob(动) → 暴民（易动的群体）",
    "morph": "词源：希腊语 morphē「形状、形式」\n核心义：形状；形态\n典型词：morphology ＝ morph(形)＋ology(学科) → 形态学；amorphous ＝ a(无)＋morph(形)＋ous → 无定形的；metamorphosis ＝ meta(变化)＋morph(形)＋osis → 变形、蜕变",
    "mort": "词源：拉丁语 mors/mortis「死亡」\n核心义：死亡\n典型词：mortal ＝ mort(死)＋al → 会死的、凡人；immortal ＝ im(不)＋mort(死)＋al → 不朽的；mortgage ＝ mort(死)＋gage(质押) → 抵押（死契）；mortality ＝ mort(死)＋ality → 死亡率",
    "mot": "词源：拉丁语 movere「移动」\n核心义：移动；运动；动机\n典型词：motion ＝ mot(动)＋ion → 运动；motive ＝ mot(动)＋ive → 动机；promote ＝ pro(向前)＋mote(动) → 促进；remote ＝ re(远)＋mote(动) → 遥远的",
    "mov": "词源：拉丁语 movere「移动」（英语 move 的来源）\n核心义：移动\n典型词：move ＝ mov(动)＋e → 移动；movement ＝ move(动)＋ment → 运动；remove ＝ re(回)＋move(动) → 移除；immovable ＝ im(不)＋mov(动)＋able → 不可移动的",
    "mun": "词源：拉丁语 munus「职责、礼物」\n核心义：职责；公共；礼物\n典型词：municipal ＝ mun(公共)＋icip(拿)＋al → 市政的；immune ＝ im(免除)＋mun(职责)＋e → 免疫的（免除公共义务）；communism ＝ com(共同)＋mun(公共)＋ism → 共产主义",
    "nat": "词源：拉丁语 nasci「出生」/natus「天生的」\n核心义：出生；天生；自然\n典型词：nation ＝ nat(出生)＋ion → 民族（同出生的群体）；native ＝ nat(生)＋ive → 本地的；nature ＝ nat(生)＋ure → 自然、天性；prenatal ＝ pre(前)＋nat(生)＋al → 产前的",
    "naut": "词源：希腊语 nautes「水手」（naus「船」）\n核心义：水手；航行\n典型词：nautical ＝ naut(航行)＋ical → 航海的；astronaut ＝ astro(星)＋naut(航行者) → 宇航员；aeronaut ＝ aero(空气)＋naut → 飞船驾驶员",
    "nav": "词源：拉丁语 navis「船」\n核心义：船；航行\n典型词：navy ＝ nav(船)＋y → 海军；navigate ＝ nav(船)＋ig(驱动)＋ate → 航行；naval ＝ nav(船)＋al → 海军的",
    "necr": "词源：希腊语 nekros「死尸」\n核心义：死尸；坏死\n典型词：necropolis ＝ necro(尸)＋polis(城) → 墓地（死者之城）；necrosis ＝ necr(死)＋osis(病) → 坏死；necromancy ＝ necro(尸)＋mancy(占卜) → 通灵术",
    "nect": "词源：拉丁语 nectere「绑、连接」\n核心义：绑；连接\n典型词：connect ＝ con(共同)＋nect(绑) → 连接；connection ＝ connect(连)＋ion → 连接；annex ＝ an(去)＋nex(绑) → 附加、吞并",
    "neur": "词源：希腊语 neuron「神经」\n核心义：神经\n典型词：neural ＝ neur(神经)＋al → 神经的；neurology ＝ neuro(神经)＋logy(学科) → 神经病学；neurosis ＝ neur(神经)＋osis(病) → 神经官能症",
    "noct": "词源：拉丁语 nox/noctis「夜」\n核心义：夜；夜间\n典型词：nocturnal ＝ noct(夜)＋urnal → 夜行性的；equinox ＝ equi(相等)＋nox(夜) → 昼夜平分点；nocturne ＝ noct(夜)＋urne → 夜曲",
    "nomin": "词源：拉丁语 nomen「名字」\n核心义：名字；命名\n典型词：nominal ＝ nomin(名)＋al → 名义上的；nominate ＝ nomin(命名)＋ate → 提名；denominate ＝ de(给予)＋nomin(名)＋ate → 命名；nomenclature ＝ nomen(名)＋clature(呼叫) → 命名法",
    "not": "词源：拉丁语 nota「标记」/notare「标记」\n核心义：标记；注意；知道\n典型词：note ＝ not(标记)＋e → 笔记、注意；notable ＝ not(注意)＋able → 值得注意的；notify ＝ not(标记→告知)＋ify → 通知；notion ＝ not(知道)＋ion → 概念",
    "nounc": "词源：拉丁语 nuntiare「报告、传达」（nuntius「信使」）\n核心义：宣布；报告\n典型词：announce ＝ an(去)＋nounce(报告) → 宣布；pronounce ＝ pro(公开)＋nounce(说) → 发音、宣告；denounce ＝ de(激烈地)＋nounce(说) → 谴责",
    "nov": "词源：拉丁语 novus「新的」\n核心义：新；新奇\n典型词：novel ＝ nov(新)＋el → 新奇的、小说；innovate ＝ in(进入)＋nov(新)＋ate → 创新；novice ＝ nov(新)＋ice → 新手；renovate ＝ re(再)＋nov(新)＋ate → 翻新",
    "numer": "词源：拉丁语 numerus「数字」\n核心义：数字；计数\n典型词：number ＝ numer(数)的变体 → 数字；numerous ＝ numer(数)＋ous → 众多的；numeral ＝ numer(数)＋al → 数词；enumerate ＝ e(出)＋numer(数)＋ate → 列举",
    "ocul": "词源：拉丁语 oculus「眼睛」\n核心义：眼睛\n典型词：oculist ＝ ocul(眼)＋ist → 眼科医生；binocular ＝ bino(双)＋cular(眼) → 双筒望远镜；monocle ＝ mono(单)＋cle(眼) → 单片眼镜；inoculate ＝ in(入)＋ocul(眼→芽眼)＋ate → 接种",
    "onym": "词源：希腊语 onyma「名字」\n核心义：名字；名称\n典型词：synonym ＝ syn(同)＋onym(名) → 同义词；antonym ＝ ant(反)＋onym(名) → 反义词；anonymous ＝ an(无)＋onym(名)＋ous → 匿名的；pseudonym ＝ pseud(假)＋onym(名) → 笔名",
    "oper": "词源：拉丁语 operari「工作」/opus「作品」\n核心义：工作；操作\n典型词：operate ＝ oper(工作)＋ate → 操作、动手术；cooperation ＝ co(共同)＋oper(工作)＋ation → 合作；opera ＝ oper(作品)＋a → 歌剧；opus ＝ opus(作品) → 作品",
    "opt": "词源：拉丁语 optare「选择」/希腊语 optos「看见的」\n核心义：选择；视力；光\n典型词：option ＝ opt(选)＋ion → 选择；optical ＝ opt(视)＋ical → 光学的；optimize ＝ optim(最佳)＋ize → 优化；optimism ＝ optim(最佳)＋ism → 乐观主义",
    "pac": "词源：拉丁语 pax/pacis「和平」\n核心义：和平；平静\n典型词：pacific ＝ pac(和平)＋ific → 和平的、太平洋；pacify ＝ pac(平静)＋ify(使……) → 使平静；pacifist ＝ pacif(和平)＋ist → 和平主义者；pact ＝ pact(约) → 条约（和平的约定）",
    "part": "词源：拉丁语 pars/partis「部分」\n核心义：部分；分开\n典型词：partial ＝ part(部分)＋ial → 部分的、偏心的；participate ＝ part(部分)＋icip(拿)＋ate → 参加（拿一部分）；particle ＝ part(部分)＋icle → 颗粒；apart ＝ a(去)＋part(分) → 分离的",
    "pass": "词源：拉丁语 patior「承受、感受」\n核心义：承受；感情；苦难\n典型词：passion ＝ pass(感情)＋ion → 激情；passive ＝ pass(承受)＋ive → 被动的；compassion ＝ com(共同)＋pass(感受)＋ion → 同情；patient ＝ pati(承受)＋ent → 病人、耐心的",
    "path": "词源：希腊语 pathos「感情、痛苦、疾病」\n核心义：感情；痛苦；疾病\n典型词：sympathy ＝ sym(共同)＋path(感受)＋y → 同情；apathy ＝ a(无)＋path(感情)＋y → 冷漠；pathetic ＝ path(痛苦)＋etic → 可怜的；pathology ＝ patho(病)＋logy(学) → 病理学",
    "ped": "词源：拉丁语 pes/pedis「足」；希腊语 paidos「儿童」\n核心义：足；儿童\n典型词：pedal ＝ ped(足)＋al → 踏板；pedestrian ＝ ped(足)＋estrian → 行人；pedicure ＝ pedi(足)＋cure(照料) → 足疗；pedagogy ＝ ped(儿童)＋agogy(引导) → 教育学",
    "pel": "词源：拉丁语 pellere「驱动、推」\n核心义：驱；推；逐\n典型词：propel ＝ pro(向前)＋pel(推) → 推进；expel ＝ ex(出)＋pel(驱) → 驱逐；repel ＝ re(回)＋pel(推) → 击退；compel ＝ com(共同)＋pel(驱) → 强迫",
    "pest": "词源：拉丁语 pestis「瘟疫」\n核心义：瘟疫；害虫\n典型词：pest ＝ pest(瘟疫) → 害虫；pesticide ＝ pest(害虫)＋i＋cide(杀) → 杀虫剂；pestilence ＝ pestil(瘟疫)＋ence → 瘟疫",
    "pet": "词源：拉丁语 petere「寻求、请求」\n核心义：寻求；请求；趋向\n典型词：compete ＝ com(共同)＋pete(寻求) → 竞争（共同追求）；appetite ＝ ap(去)＋pet(求)＋ite → 食欲；petition ＝ pet(请求)＋ition → 请愿；repetition ＝ re(再)＋pet(求)＋ition → 重复",
    "petr": "词源：希腊语 petra「岩石」\n核心义：岩石；石化\n典型词：petroleum ＝ petr(石)＋oleum(油) → 石油；petrify ＝ petr(石)＋ify(使……) → 使石化、使吓呆；petrel ＝ petr(石)＋el → 海燕（崖栖鸟）",
    "phil": "词源：希腊语 philos「爱的」/philein「爱」\n核心义：爱；爱好\n典型词：philosophy ＝ philo(爱)＋sophy(智慧) → 哲学；philanthropy ＝ phil(爱)＋anthropy(人类) → 慈善；audiophile ＝ audio(声音)＋phile(爱) → 音响发烧友；bibliophile ＝ biblio(书)＋phile → 爱书者",
    "phon": "词源：希腊语 phōnē「声音」\n核心义：声音\n典型词：telephone ＝ tele(远)＋phone(声) → 电话；symphony ＝ sym(共同)＋phony(声) → 交响乐；microphone ＝ micro(小)＋phone(声) → 麦克风；phonetics ＝ phon(声)＋etics → 语音学",
    "phot": "词源：希腊语 phōs/photos「光」\n核心义：光\n典型词：photograph ＝ photo(光)＋graph(画) → 照片；photosynthesis ＝ photo(光)＋synthesis(合成) → 光合作用；photon ＝ phot(光)＋on(粒子) → 光子",
    "plac": "词源：拉丁语 placere「取悦」/placare「平息」\n核心义：取悦；平静\n典型词：placid ＝ plac(平静)＋id → 平静的；placate ＝ plac(平息)＋ate → 抚慰；complacent ＝ com(加强)＋plac(满足)＋ent → 自满的；please ＝ pleas(取悦)的变体 → 使高兴",
    "plen": "词源：拉丁语 plenus「满的」\n核心义：满；全；充分\n典型词：plenty ＝ plen(满)＋ty → 丰富；plentiful ＝plen(满)＋tiful → 丰富的；plenary ＝ plen(全)＋ary → 全体的；complete ＝ com(完全)＋plete(满) → 完成；replenish ＝ re(再)＋plen(满)＋ish → 补充",
    "pod": "词源：希腊语 pous/podos「足」\n核心义：足\n典型词：podium ＝ pod(足)＋ium(站处) → 讲台；tripod ＝ tri(三)＋pod(足) → 三脚架；pseudopod ＝ pseudo(假)＋pod(足) → 伪足；antipodes ＝ anti(相反)＋podes(足) → 对跖地（脚对脚的地方）",
    "polis": "词源：希腊语 polis「城邦」\n核心义：城市；城邦；政治\n典型词：police ＝ polis(城)＋ice → 警察（城市管理）；politics ＝ polit(城邦)＋ics → 政治；metropolis ＝ metro(母)＋polis(城) → 大都市；cosmopolitan ＝ cosmo(世界)＋polit(城)＋an → 世界性的",
    "pon": "词源：拉丁语 ponere「放置」\n核心义：放；置\n典型词：position ＝ pos(放)＋ition → 位置；postpone ＝ post(后)＋pone(放) → 推迟（往后放）；component ＝ com(共同)＋pon(放)＋ent → 组成部分；opponent ＝ op(相反)＋pon(放)＋ent → 对手",
    "popul": "词源：拉丁语 populus「人民」\n核心义：人民；民众；人口\n典型词：popular ＝ popul(民众)＋ar → 受欢迎的；population ＝ popul(人)＋ation → 人口；populist ＝ popul(民众)＋ist → 民粹主义者；populace ＝ populac(民众)＋e → 大众",
    "port": "词源：拉丁语 portare「搬运」\n核心义：搬运；携带；港口\n典型词：portable ＝ port(携带)＋able → 便携的；transport ＝ trans(转移)＋port(搬) → 运输；export ＝ ex(出)＋port(搬) → 出口；import ＝ im(入)＋port(搬) → 进口；deport ＝ de(离开)＋port → 驱逐出境",
    "pos": "词源：拉丁语 ponere 的分词词干（与 pon 同源）\n核心义：放置；位置\n典型词：compose ＝ com(共同)＋pose(放) → 组成、作曲；deposit ＝ de(下)＋pos(放)＋it → 存放、存款；expose ＝ ex(出)＋pose(放) → 暴露；dispose ＝ dis(分开)＋pose(放) → 处理",
    "preci": "词源：拉丁语 pretium「价值、价格」\n核心义：价值；价格\n典型词：price ＝ preci(价)的变体 → 价格；precious ＝ preci(珍贵)＋ous → 珍贵的；appreciate ＝ ap(去)＋preci(价值)＋ate → 欣赏、增值；depreciate ＝ de(降低)＋preci(价)＋ate → 贬值",
    "press": "词源：拉丁语 premere「压」\n核心义：压；挤压\n典型词：press ＝ press(压) → 按压、新闻界；pressure ＝ press(压)＋ure → 压力；express ＝ ex(出)＋press(压→挤出) → 表达、快递；impress ＝ im(入)＋press(压) → 使印象深刻；compress ＝ com(一起)＋press(压) → 压缩",
    "prim": "词源：拉丁语 primus「第一」\n核心义：第一；首要；原始\n典型词：primary ＝ prim(第一)＋ary → 首要的；primitive ＝ prim(原始)＋itive → 原始的；prime ＝ prim(首)＋e → 最初的、素数；premier ＝ prem(第一)＋ier → 首相、首要的",
    "psych": "词源：希腊语 psychē「灵魂、精神」\n核心义：心理；精神；灵魂\n典型词：psychology ＝ psych(心理)＋ology(学科) → 心理学；psychic ＝ psych(精神)＋ic → 精神的、通灵的；psychiatry ＝ psych(精神)＋iatry(治疗) → 精神病学",
    "pugn": "词源：拉丁语 pugnare「打斗」（pugnus「拳头」）\n核心义：打斗；拳头\n典型词：pugnacious ＝ pugn(斗)＋acious → 好斗的；pugilist ＝ pug(拳)＋ilist → 拳击手；impugn ＝ im(去)＋pugn(击) → 质疑、抨击",
    "puls": "词源：拉丁语 pellere「驱动」的分词词干（与 pel 同源）\n核心义：驱动；推；脉冲\n典型词：impulse ＝ im(内)＋puls(推)＋e → 冲动、脉冲；compulsory ＝ com(加强)＋puls(驱)＋ory → 强制的；expulsion ＝ ex(出)＋puls(驱)＋ion → 驱逐",
    "punct": "词源：拉丁语 pungere「刺」\n核心义：刺；点；准时\n典型词：punctual ＝ punct(点→正点)＋ual → 准时的；punctuate ＝ punct(点)＋uate → 加标点；acupuncture ＝ acu(针)＋punct(刺)＋ure → 针灸；puncture ＝ punct(刺)＋ure → 刺破",
    "put": "词源：拉丁语 putare「思考、计算、认为」\n核心义：思考；计算；认为\n典型词：computer ＝ com(共同)＋put(计算)＋er → 计算机；dispute ＝ dis(分开)＋pute(想) → 争论；reputation ＝ re(再)＋put(想)＋ation → 名誉（公众再三相想之物）；compute ＝ com(共同)＋pute(算) → 计算",
    "quest": "词源：拉丁语 quaerere「寻求」（经由古法语）\n核心义：寻求；询问\n典型词：quest ＝ quest(求) → 探索；question ＝ quest(问)＋ion → 问题；conquest ＝ con(完全)＋quest(求) → 征服；questor ＝ quest(求→查)＋or → 检察官",
    "quir": "词源：拉丁语 quaerere 的变体（与 quest 同源）\n核心义：寻求；询问\n典型词：inquire ＝ in(入)＋quire(问) → 询问；require ＝ re(再)＋quire(求) → 需要；acquire ＝ ac(去)＋quire(求) → 获得；inquiry ＝ in(入)＋quir(问)＋y → 调查",
    "rat": "词源：拉丁语 ratio「计算、理性」（reri「思考」）\n核心义：计算；理性；理由\n典型词：rational ＝ ration(理性)＋al → 理性的；ratio ＝ ratio(算) → 比率；ration ＝ rat(计算→定量)＋ion → 定量配给；rationale ＝ ration(理性)＋ale → 基本原理",
    "rect": "词源：拉丁语 rectus「直的、正确的」\n核心义：直；正；纠正\n典型词：correct ＝ cor(加强)＋rect(正) → 纠正、正确的；rectangle ＝ rect(直)＋angle(角) → 矩形；erect ＝ e(出→立起)＋rect(直) → 直立、建造；rectify ＝ rect(正)＋ify(使……) → 纠正",
    "reg": "词源：拉丁语 rex「王」/regere「统治、引导」\n核心义：统治；王；引导\n典型词：regime ＝ reg(统治)＋ime → 政权；regulate ＝ reg(引导)＋ulate → 管理、调节；regent ＝ reg(统治)＋ent → 摄政者；regal ＝ reg(王)＋al → 帝王般的",
    "rod": "词源：拉丁语 rodere「咬、啃」\n核心义：咬；侵蚀\n典型词：corrode ＝ cor(加强)＋rode(咬) → 腐蚀；erode ＝ e(出)＋rode(咬) → 侵蚀；rodent ＝ rod(啃)＋ent → 啮齿动物；corrosion ＝ cor(加强)＋ros(咬)＋ion → 腐蚀",
    "rot": "词源：拉丁语 rotare「旋转」（rota「轮子」）\n核心义：旋转；轮\n典型词：rotate ＝ rot(转)＋ate → 旋转；rotary ＝ rot(转)＋ary → 旋转的；rotor ＝ rot(转)＋or → 转子；rotunda ＝ rotund(圆)＋a → 圆形建筑",
    "rupt": "词源：拉丁语 rumpere「打破」\n核心义：破裂；打破\n典型词：erupt ＝ e(出)＋rupt(破) → 爆发；interrupt ＝ inter(中间)＋rupt(破) → 打断；bankrupt ＝ bank(柜台)＋rupt(破) → 破产的；corrupt ＝ cor(加强)＋rupt(破) → 腐败的",
    "sacr": "词源：拉丁语 sacer「神圣的」\n核心义：神圣；祭祀\n典型词：sacred ＝ sacr(神圣)＋ed → 神圣的；sacrifice ＝ sacri(神圣)＋fice(做) → 牺牲（做祭品）；sacrament ＝ sacr(圣)＋ament → 圣礼；sacrilege ＝ sacri(圣)＋lege(拿) → 渎圣",
    "salut": "词源：拉丁语 salus「健康」/salutare「问候」\n核心义：健康；问候；致敬\n典型词：salute ＝ salut(健康→祝安)＋e → 敬礼；salutation ＝ salut(问候)＋ation → 问候语；salubrious ＝ salubr(健康)＋ious → 有益健康的；salutary ＝ salut(健康)＋ary → 有益的",
    "sanit": "词源：拉丁语 sanitas「健康」（sanus「健康的」）\n核心义：健康；卫生\n典型词：sanitary ＝ sanit(健康)＋ary → 卫生的；sanitation ＝ sanit(卫生)＋ation → 卫生设施；sanatorium ＝ sanat(健康)＋orium(场所) → 疗养院；sane ＝ san(健康)＋e → 神志正常的",
    "scend": "词源：拉丁语 scandere「攀爬」\n核心义：爬；攀登；上升\n典型词：ascend ＝ a(去)＋scend(爬) → 上升；descend ＝ de(下)＋scend(爬) → 下降；transcend ＝ trans(越过)＋scend(爬) → 超越",
    "sci": "词源：拉丁语 scire「知道」\n核心义：知道；知识\n典型词：science ＝ sci(知)＋ence → 科学；conscious ＝ con(共同)＋sci(知)＋ous → 意识到的；omniscient ＝ omni(全)＋sci(知)＋ent → 全知的；subconscious ＝ sub(下)＋conscious → 潜意识的",
    "scop": "词源：希腊语 skopein「观察」\n核心义：观察；观察仪器\n典型词：telescope ＝ tele(远)＋scope(观察器) → 望远镜；microscope ＝ micro(微)＋scope → 显微镜；stethoscope ＝ stetho(胸)＋scope → 听诊器；periscope ＝ peri(周围)＋scope → 潜望镜",
    "scrib": "词源：拉丁语 scribere「写」\n核心义：写\n典型词：scribble ＝ scrib(写)＋ble → 潦草地写；describe ＝ de(下)＋scribe(写) → 描述；subscribe ＝ sub(下)＋scribe(写→签名) → 订阅；prescribe ＝ pre(先)＋scribe(写) → 开处方、规定",
    "script": "词源：拉丁语 scribere 的分词词干（与 scrib 同源）\n核心义：写；手迹\n典型词：script ＝ script(写) → 剧本、手迹；manuscript ＝ manu(手)＋script(写) → 手稿；transcript ＝ trans(转)＋script(写) → 抄本；scripture ＝ script(写)＋ure → 经文",
    "sect": "词源：拉丁语 secare「切割」\n核心义：切；割；派别\n典型词：section ＝ sect(切)＋ion → 部分、截面；dissect ＝ dis(分开)＋sect(切) → 解剖；intersect ＝ inter(之间)＋sect(切) → 相交；bisect ＝ bi(二)＋sect(切) → 平分",
    "sen": "词源：拉丁语 senex「老的」\n核心义：老；年长\n典型词：senior ＝ sen(老)＋ior → 年长的；senate ＝ sen(老)＋ate → 参议院（元老议事机构）；senile ＝ sen(老)＋ile → 老年的、衰老的；sir ＝ sen 的变体 → 先生",
    "sens": "词源：拉丁语 sentire「感觉」\n核心义：感觉；感官\n典型词：sense ＝ sens(感觉)＋e → 感觉、意义；sensory ＝ sens(感觉)＋ory → 感官的；sensitive ＝ sens(感觉)＋itive → 敏感的；sensation ＝ sens(感觉)＋ation → 感觉、轰动",
    "sent": "词源：拉丁语 sentire 的词干（与 sens 同源）\n核心义：感觉；意见\n典型词：sentiment ＝ sent(感觉)＋iment → 情绪；consent ＝ con(共同)＋sent(感觉) → 同意（感觉一致）；dissent ＝ dis(分开)＋sent(感) → 异议；sentimental ＝ sentiment(情感)＋al → 多愁善感的",
    "sequ": "词源：拉丁语 sequi「跟随」\n核心义：跟随；相继\n典型词：sequence ＝ sequ(随)＋ence → 序列；consequence ＝ con(共同)＋sequ(随)＋ence → 后果（随之而来之物）；subsequent ＝ sub(后)＋sequ(随)＋ent → 随后的；sequel ＝ sequ(随)＋el → 续集",
    "sert": "词源：拉丁语 serere「放置、连接」\n核心义：放置；连接；断言\n典型词：insert ＝ in(入)＋sert(放) → 插入；assert ＝ as(去)＋sert(放置→坚持) → 断言；desert ＝ de(离开)＋sert(连接) → 抛弃、沙漠；exert ＝ ex(出)＋ert(放→发力) → 施加",
    "serv": "词源：拉丁语 servire「服务」/servare「保持、保存」\n核心义：服务；保持；保存\n典型词：serve ＝ serv(服务)＋e → 服务；conserve ＝ con(共同)＋serve(保存) → 保存；reserve ＝ re(回)＋serve(保存) → 预订、储备；preserve ＝ pre(先)＋serve(保存) → 保护、保鲜",
    "sid": "词源：拉丁语 sedere「坐」\n核心义：坐；安顿\n典型词：preside ＝ pre(前)＋side(坐) → 主持（坐在前面）；reside ＝ re(回)＋side(坐) → 居住；sediment ＝ sedi(沉坐)＋ment → 沉积物；sedentary ＝ sedent(坐)＋ary → 久坐的",
    "sign": "词源：拉丁语 signum「标记」\n核心义：标记；信号；签名\n典型词：signal ＝ sign(标记)＋al → 信号；signature ＝ sign(标记)＋ature → 签名；significant ＝ sign(标记)＋ific(做)＋ant → 重要的（值得标记的）；design ＝ de(下)＋sign(标记) → 设计",
    "soci": "词源：拉丁语 socius「同伴、盟友」\n核心义：同伴；社会；联合\n典型词：social ＝ soci(同伴)＋al → 社会的；society ＝ soci(同伴)＋ety → 社会；associate ＝ as(去)＋soci(联合)＋ate → 联系、同事；sociology ＝ socio(社会)＋logy(学) → 社会学",
    "sol": "词源：拉丁语 sol「太阳」\n核心义：太阳\n典型词：solar ＝ sol(太阳)＋ar → 太阳的；solarium ＝ sol(阳)＋arium(场所) → 日光浴室；parasol ＝ para(遮)＋sol(阳) → 遮阳伞；solstice ＝ sol(阳)＋stice(停) → 至日",
    "solut": "词源：拉丁语 solvere「松开」的分词词干\n核心义：松开；溶解；解决\n典型词：solution ＝ solut(松)＋ion → 解决、溶液；dissolution ＝ dis(分开)＋solut(松)＋ion → 溶解、解散；absolute ＝ ab(离开)＋solut(松)＋e → 绝对的（不受约束的）",
    "solv": "词源：拉丁语 solvere「松开、解决」\n核心义：松开；解决\n典型词：solve ＝ solv(松)＋e → 解决；dissolve ＝ dis(分开)＋solve(松) → 溶解；resolve ＝ re(再)＋solve(松) → 决心、解决；solvent ＝ solv(松)＋ent → 溶剂、有偿付能力的",
    "somn": "词源：拉丁语 somnus「睡眠」\n核心义：睡眠\n典型词：insomnia ＝ in(无)＋somn(眠)＋ia → 失眠；somnolent ＝ somn(眠)＋olent → 困倦的；somnambulist ＝ somn(眠)＋ambul(走)＋ist → 梦游者",
    "son": "词源：拉丁语 sonare「发声」\n核心义：声音；发声\n典型词：sonic ＝ son(声)＋ic → 声音的；resonance ＝ re(回)＋son(声)＋ance → 共鸣；consonant ＝ con(共同)＋son(声)＋ant → 辅音（一起发声）；unison ＝ uni(一)＋son(声) → 齐唱、一致",
    "soph": "词源：希腊语 sophos「智慧的」\n核心义：智慧\n典型词：sophisticated ＝ sophistic(智慧→世故)＋ated → 复杂精密的、老练的；philosopher ＝ philo(爱)＋sopher(智慧) → 哲学家；sophomore ＝ sopho(智慧)＋more(愚人) → 大学二年级生（半智半愚）",
    "spect": "词源：拉丁语 specere「看」\n核心义：看；注视；外观\n典型词：inspect ＝ in(向内)＋spect(看) → 检查；respect ＝ re(回)＋spect(看) → 尊重（反复看）；prospect ＝ pro(向前)＋spect(看) → 前景；spectator ＝ spectat(观)＋or → 观众；suspect ＝ su(b)(下)＋spect(看) → 怀疑（由下打量）",
    "spher": "词源：希腊语 sphaira「球、球体」\n核心义：球；球体；圈层\n典型词：sphere ＝ spher(球)＋e → 球体、领域；atmosphere ＝ atmo(汽)＋sphere(球) → 大气层；hemisphere ＝ hemi(半)＋sphere(球) → 半球；biosphere ＝ bio(生命)＋sphere → 生物圈",
    "spir": "词源：拉丁语 spirare「呼吸」\n核心义：呼吸；气息；精神\n典型词：inspire ＝ in(入)＋spire(吸) → 鼓舞（吸入灵气）；expire ＝ ex(出)＋pire(呼吸) → 呼气、到期；conspire ＝ con(共同)＋spire(呼吸) → 共谋（同呼吸）；spirit ＝ spir(气息)＋it → 精神",
    "splend": "词源：拉丁语 splendere「发光」\n核心义：发光；辉煌\n典型词：splendid ＝ splend(发光)＋id → 辉煌的；splendor ＝ splend(光)＋or → 光彩；resplendent ＝ re(加强)＋splend(发亮)＋ent → 灿烂的",
    "stabil": "词源：拉丁语 stabilis「稳固的」（stare「站立」）\n核心义：站立；稳定\n典型词：stable ＝ stab(站)＋le → 稳定的、马厩；stabilize ＝ stabil(稳)＋ize → 使稳定；stability ＝ stabil(稳)＋ity → 稳定性；establish ＝ establ(稳固)＋ish → 建立",
    "stat": "词源：拉丁语 stare「站立」\n核心义：站立；位置；状态\n典型词：station ＝ stat(站)＋ion → 车站、岗位；statue ＝ stat(立)＋ue → 雕像；status ＝ stat(立→位)＋us → 地位、状态；static ＝ stat(立→不动)＋ic → 静态的；ecstasy ＝ ec(出)＋stasy(立) → 狂喜（站立不稳）",
    "stell": "词源：拉丁语 stella「星」\n核心义：星\n典型词：stellar ＝ stell(星)＋ar → 恒星的、优秀的；constellation ＝ con(共同)＋stell(星)＋ation → 星座；interstellar ＝ inter(之间)＋stellar(星) → 星际的",
    "strain": "词源：拉丁语 stringere「拉紧」（经古法语变体）\n核心义：拉紧；束缚；压力\n典型词：strain ＝ strain(拉紧) → 拉紧、压力；constrain ＝ con(一起)＋strain(拉紧) → 限制；overstrain ＝ over(过度)＋strain(紧) → 过劳；restrain ＝ re(回)＋strain(拉) → 抑制",
    "strict": "词源：拉丁语 stringere 的分词词干\n核心义：拉紧；严格\n典型词：strict ＝ strict(拉紧) → 严格的；restrict ＝ re(回)＋strict(拉) → 限制；constrict ＝ con(一起)＋strict(紧) → 收缩；district ＝ di(分开)＋strict(拉界) → 区域",
    "string": "词源：拉丁语 stringere「捆绑、拉紧」\n核心义：捆绑；弦；拉紧\n典型词：string ＝ string(捆) → 细绳、弦；stringent ＝ string(紧)＋ent → 严格的（规定）；astringent ＝ a(去)＋string(紧)＋ent → 收敛性的",
    "struct": "词源：拉丁语 struere「建造、堆叠」\n核心义：建造；构造\n典型词：structure ＝ struct(建)＋ure → 结构；construct ＝ con(共同)＋struct(建) → 建造；instruct ＝ in(内)＋struct(建→教) → 教导；destroy ＝ de(去除)＋stroy(建) → 破坏；infrastructure ＝ infra(下部)＋structure → 基础设施",
    "sum": "词源：拉丁语 sumere「拿取」\n核心义：拿取；承担；假定\n典型词：assume ＝ as(去)＋sume(拿) → 假定、承担；consume ＝ con(完全)＋sume(拿) → 消耗；resume ＝ re(回)＋sume(拿) → 恢复（重新拿起）；presume ＝ pre(先)＋sume(拿) → 推测",
    "tact": "词源：拉丁语 tangere「接触」\n核心义：接触；触觉；机智\n典型词：contact ＝ con(共同)＋tact(触) → 联系；tactile ＝ tact(触)＋ile → 触觉的；tangible ＝ tang(触)＋ible(可……的) → 有形的；intact ＝ in(未)＋tact(触) → 完好无损的",
    "tain": "词源：拉丁语 tenere「持有、保持」\n核心义：持；保持；容纳\n典型词：contain ＝ con(共同)＋tain(持) → 包含；maintain ＝ main(手→man)＋tain(持) → 维持（用手持住）；obtain ＝ ob(靠近)＋tain(持) → 获得；tenant ＝ ten(持)＋ant → 房客（持有房屋者）",
    "techn": "词源：希腊语 technē「技艺、技术」\n核心义：技术；技艺\n典型词：technology ＝ techn(技术)＋ology(学科) → 技术；technique ＝ techn(技)＋ique → 技巧；technical ＝ techn(技)＋ical → 技术的；technician ＝ techn(技)＋ician → 技师",
    "tect": "词源：拉丁语 tegere「遮盖」\n核心义：遮盖；掩盖\n典型词：detect ＝ de(去除)＋tect(盖) → 察觉（揭开）；protect ＝ pro(在前)＋tect(盖) → 保护（遮在前面）；architect ＝ archi(首席)＋tect(建造者) → 建筑师",
    "tempor": "词源：拉丁语 tempus「时间」\n核心义：时间；时节\n典型词：temporary ＝ tempor(时间)＋ary → 暂时的；contemporary ＝ con(共同)＋tempor(时)＋ary → 同时代的；tempo ＝ tempor(时)＋o → 节奏；temporize ＝ tempor(时)＋ize → 拖延（顺应时势）",
    "ten": "词源：拉丁语 tenere「持有」（tain/tin 的原形）\n核心义：持；握；保持\n典型词：tenacious ＝ ten(持)＋acious → 顽强的；tenant ＝ ten(持)＋ant → 房客；tenure ＝ ten(持)＋ure → 任期、终身职位；tent ＝ tent(张→持开) → 帐篷",
    "tend": "词源：拉丁语 tendere「伸展、趋向」\n核心义：伸展；趋向；照料\n典型词：tend ＝ tend(伸→朝向) → 趋向、照料；extend ＝ ex(出)＋tend(伸) → 延伸；attend ＝ at(去)＋tend(伸→倾注) → 出席、照料；contend ＝ con(共同)＋tend(伸) → 竞争、主张",
    "tens": "词源：拉丁语 tendere 的分词词干\n核心义：伸展；张力\n典型词：intense ＝ in(内)＋tense(拉紧) → 强烈的；tension ＝ tens(拉)＋ion → 张力、紧张；extensive ＝ ex(出)＋tens(伸)＋ive → 广泛的；hypertension ＝ hyper(过度)＋tension → 高血压",
    "tent": "词源：拉丁语 tendere 的分词词干（与 tens 同源）\n核心义：伸展；趋向\n典型词：attention ＝ at(去)＋tent(伸→倾注)＋ion → 注意；intention ＝ in(向)＋tent(伸)＋ion → 意图（心之所向）；tentative ＝ tent(伸→尝试)＋ative → 试探性的；extent ＝ ex(出)＋tent(伸) → 程度、范围",
    "termin": "词源：拉丁语 terminus「界限、终点」\n核心义：界限；终点\n典型词：terminal ＝ termin(终点)＋al → 终点站、晚期的；terminate ＝ termin(终止)＋ate → 终止；determine ＝ de(下)＋termin(界)＋e → 决定（定下界限）；interminable ＝ inter(之间无)＋min(界)＋able → 冗长的",
    "terr": "词源：拉丁语 terra「土地」\n核心义：土地；陆地\n典型词：territory ＝ terr(地)＋it(走)＋ory → 领土（走过的土地）；terrain ＝ terr(地)＋ain → 地形；terrestrial ＝ terre(陆地)＋strial → 陆地的；Mediterranean ＝ medi(中)＋terra(地)＋nean → 地中海",
    "test": "词源：拉丁语 testis「见证人」（本义「第三者」）\n核心义：见证；证明；考验\n典型词：testify ＝ test(见证)＋ify → 作证；testimony ＝ test(证)＋imony → 证词；contest ＝ con(共同)＋test(见证→比试) → 竞赛；protest ＝ pro(公开)＋test(证) → 抗议（公开作证）",
    "text": "词源：拉丁语 texere「编织」\n核心义：编织；文本\n典型词：text ＝ text(编织→织成之文) → 文本；textile ＝ text(织)＋ile → 纺织品；texture ＝ text(织)＋ure → 质地；context ＝ con(共同)＋text(织) → 上下文（共同编织的部分）",
    "therm": "词源：希腊语 thermē「热」\n核心义：热；温度\n典型词：thermometer ＝ thermo(热)＋meter(计) → 温度计；thermal ＝ therm(热)＋al → 热的；thermostat ＝ thermo(热)＋stat(稳定器) → 恒温器；isotherm ＝ iso(等)＋therm(温) → 等温线",
    "thes": "词源：希腊语 tithenai「放置」\n核心义：放置；提出\n典型词：thesis ＝ thes(放)＋is → 论文（提出的观点）；hypothesis ＝ hypo(下)＋thesis(放置) → 假设（放在下面的基础）；synthesis ＝ syn(共同)＋thesis(放) → 合成；antithesis ＝ anti(反)＋thesis → 对立",
    "tim": "词源：拉丁语 timere「害怕」\n核心义：害怕；胆怯\n典型词：timid ＝ tim(怕)＋id → 胆小的；intimidate ＝ in(使)＋timid(胆怯)＋ate → 恐吓；timorous ＝ tim(惧)＋orous → 胆怯的",
    "tin": "词源：拉丁语 tenere 的词干变体（与 tain 同源）\n核心义：持；保持\n典型词：continue ＝ con(共同)＋tin(持)＋ue → 继续；continent ＝ conti(持在一起)＋nent → 大陆、自制的；retinue ＝ re(回)＋tin(持)＋ue → 随行人员",
    "tom": "词源：希腊语 temnein「切割」\n核心义：切；割\n典型词：atom ＝ a(不)＋tom(切) → 原子（不可再分割之物）；anatomy ＝ ana(分开)＋tomy(切) → 解剖学；dichotomy ＝ dicho(二)＋tomy(分) → 二分法；appendectomy ＝ append(阑尾)＋ecto(切)＋my → 阑尾切除术",
    "ton": "词源：希腊语 tonos「张力、音调」\n核心义：音调；张力\n典型词：tone ＝ ton(调)＋e → 音调、语气；monotone ＝ mono(单)＋tone(调) → 单调；tonic ＝ ton(张力→滋补)＋ic → 滋补品；detonate ＝ de(离)＋ton(音→爆响)＋ate → 引爆",
    "tors": "词源：拉丁语 torquere「扭转」\n核心义：扭转\n典型词：torsion ＝ tors(扭)＋ion → 扭转力；extort ＝ ex(出)＋tort(扭→强取) → 敲诈；distortion ＝ dis(离)＋tort(扭)＋ion → 扭曲；contort ＝ con(加强)＋tort(扭) → 扭弯",
    "tort": "词源：拉丁语 torquere「扭转」（torse 的词干）\n核心义：扭；弯；折磨\n典型词：torture ＝ tort(扭)＋ure → 折磨（使身体扭曲）；tortuous ＝ tort(弯)＋uous → 曲折的；retort ＝ re(回)＋tort(扭) → 反驳（扭转回去）；torque ＝ torqu(扭)＋e → 扭矩",
    "tot": "词源：拉丁语 totus「全部的」\n核心义：全部；整体\n典型词：total ＝ tot(全)＋al → 总的；totality ＝ tot(全)＋ality → 全体；totalize ＝ tot(全)＋alize → 总计；entirety ＝ en(使)＋tire(=tot 全)＋ty → 整体",
    "tour": "词源：拉丁语 tornus「车床、旋转」（经法语 tour）\n核心义：转；巡回\n典型词：tour ＝ tour(转→绕行) → 旅行；tourism ＝ tour(游)＋ism → 旅游业；detour ＝ de(偏离)＋tour(转) → 绕行；tournament ＝ tourna(转→比武)＋ment → 锦标赛",
    "tox": "词源：希腊语 toxikon「毒箭」（toxon「弓」）\n核心义：毒\n典型词：toxic ＝ tox(毒)＋ic → 有毒的；toxin ＝ tox(毒)＋in → 毒素；toxicology ＝ toxico(毒)＋logy(学) → 毒理学；detoxify ＝ de(去除)＋tox(毒)＋ify → 解毒",
    "tract": "词源：拉丁语 trahere「拉、拖」\n核心义：拉；拖；吸引\n典型词：attract ＝ at(去)＋tract(拉) → 吸引；contract ＝ con(共同)＋tract(拉) → 合同、收缩；extract ＝ ex(出)＋tract(拉) → 提取；tractor ＝ tract(拉)＋or → 拖拉机；distract ＝ dis(分开)＋tract(拉) → 使分心",
    "trib": "词源：拉丁语 tribuere「给予、分配」（tribus「部落」）\n核心义：给予；分配；部落\n典型词：contribute ＝ con(共同)＋tribute(给) → 贡献；distribute ＝ dis(分开)＋tribute(给) → 分配；tribute ＝ trib(给)＋ute → 贡品、致敬；attribute ＝ at(去)＋tribute(给) → 归因于、属性",
    "turb": "词源：拉丁语 turbare「搅乱」（turba「混乱人群」）\n核心义：搅乱；骚动\n典型词：disturb ＝ dis(分开)＋turb(搅) → 打扰；turbulent ＝ turb(乱)＋ulent → 动荡的；turbine ＝ turb(旋→转)＋ine → 涡轮；turbulence ＝ turb(乱)＋ulence → 湍流",
    "ultim": "词源：拉丁语 ultimus「最后的」（ultra「超出」的最高级）\n核心义：最后；终极\n典型词：ultimate ＝ ultim(最后)＋ate → 最终的；ultimatum ＝ ultim(最后)＋atum → 最后通牒；penultimate ＝ pen(几乎)＋ultimate → 倒数第二的",
    "umbr": "词源：拉丁语 umbra「影子」\n核心义：影；阴\n典型词：umbrella ＝ umbr(影)＋ella(小) → 雨伞（遮阳小影）；umbrage ＝ umbr(荫)＋age → 树荫、不快；penumbra ＝ pen(几乎)＋umbra(影) → 半影；adumbrate ＝ ad(去)＋umbr(影)＋ate → 勾画、预示",
    "urb": "词源：拉丁语 urbs「城市」\n核心义：城市\n典型词：urban ＝ urb(城)＋an → 城市的；suburb ＝ sub(近下)＋urb(城) → 郊区；urbane ＝ urban(城→优雅)＋e → 温文尔雅的；conurbation ＝ con(共同)＋urb(城)＋ation → 集合城市",
    "ust": "词源：拉丁语 ustus「燃烧的」（urere「烧」的分词）\n核心义：燃烧；烧\n典型词：combustion ＝ com(加强)＋bust(烧)＋ion → 燃烧；combustible ＝ com(加强)＋bust(烧)＋ible → 易燃的；combustion engine → 内燃机",
    "util": "词源：拉丁语 uti「使用」/utilis「有用的」\n核心义：使用；有用\n典型词：utilize ＝ util(用)＋ize → 利用；utility ＝ util(用)＋ity → 效用、公用事业；utilitarian ＝ utilit(有用)＋arian → 功利主义的；useful ＝ use(用)＋ful → 有用的",
    "vac": "词源：拉丁语 vacare「空出」/vacuus「空的」\n核心义：空；空闲；空缺\n典型词：vacant ＝ vac(空)＋ant → 空的；vacation ＝ vac(空→空闲)＋ation → 假期；vacuum ＝ vacu(空)＋um → 真空；evacuate ＝ e(出)＋vacu(空)＋ate → 撤离（使变空）",
    "vad": "词源：拉丁语 vadere「行走、前进」\n核心义：走；前进\n典型词：invade ＝ in(入)＋vade(走) → 入侵；evade ＝ e(出)＋vade(走) → 逃避（走开）；pervade ＝ per(贯穿)＋vade(走) → 弥漫",
    "vag": "词源：拉丁语 vagari「漫游」（vagus「游移的」）\n核心义：漫游；游移；模糊\n典型词：vague ＝ vag(游移)＋ue → 模糊的；vagrant ＝ vag(漫游)＋rant → 流浪者；extravagant ＝ extra(出)＋vag(游)＋ant → 奢侈的（游出正轨）；divagate ＝ di(离)＋vag(游)＋ate → 离题",
    "vail": "词源：拉丁语 valere「强壮、有价值」\n核心义：价值；强壮；有效\n典型词：available ＝ a(去)＋vail(价值)＋able → 可获得的；prevail ＝ pre(前)＋vail(强) → 盛行、获胜；avail ＝ a(去)＋vail(价值) → 有益于；equivalent ＝ equi(相等)＋val(值)＋ent → 等价的",
    "val": "词源：拉丁语 valere「强壮、有价值」\n核心义：价值；强壮\n典型词：value ＝ val(价值)＋ue → 价值；valid ＝ val(强→有效)＋id → 有效的；invalid ＝ in(不)＋valid → 无效的、病弱的；valor ＝ val(勇)＋or → 勇猛；equivalent ＝ equi(等)＋val(值)＋ent → 等价物",
    "van": "词源：拉丁语 vanus「空的」（vanescere「消散」）\n核心义：空；虚荣；消逝\n典型词：vanish ＝ van(空→消失)＋ish → 消失；vanity ＝ van(空→虚)＋ity → 虚荣；vanity fair → 虚荣的市场（名利场）；evanescent ＝ e(出)＋vanes(消散)＋cent → 逐渐消失的",
    "vari": "词源：拉丁语 varius「变化的、多样的」\n核心义：变化；多样\n典型词：various ＝ vari(多样)＋ous → 各种各样的；variety ＝ vari(变)＋ety → 多样性；variable ＝ vari(变)＋able → 可变的；variation ＝ vari(变)＋ation → 变化；invariable ＝ in(不)＋variable → 不变的",
    "vect": "词源：拉丁语 vehere「运载」的分词词干\n核心义：运载；载体\n典型词：vector ＝ vect(运)＋or → 矢量、载体；vection ＝ vect(运)＋ion → 运送；convection ＝ con(共同)＋vect(运)＋ion → 对流；conveyor ＝ con(共同)＋vey(运)＋or → 传送带",
    "veh": "词源：拉丁语 vehere「携带、运载」\n核心义：运载；车辆\n典型词：vehicle ＝ veh(运)＋icle(工具) → 车辆、媒介；vehicular ＝ vehicul(车辆)＋ar → 车辆的；convey ＝ con(共同)＋vey(运) → 传达、运送",
    "ven": "词源：拉丁语 venire「来」\n核心义：来；到来；发生\n典型词：venture ＝ vent(来→冒险而来)＋ure → 冒险；convene ＝ con(共同)＋vene(来) → 召集；prevent ＝ pre(先)＋vent(来) → 阻止（先来拦截）；intervene ＝ inter(中间)＋vene(来) → 干预；avenue ＝ a(去)＋ven(来)＋ue → 大道（来路）",
    "vent": "词源：拉丁语 venire「来」/ventus「风」\n核心义：来；风\n典型词：advent ＝ ad(去)＋vent(来) → 出现、来临；event ＝ e(出)＋vent(来) → 事件（出来的事）；vent ＝ vent(风) → 通风口；ventilate ＝ vent(风)＋ilate → 通风",
    "ver": "词源：拉丁语 verus「真实的」\n核心义：真实；真实之物\n典型词：verify ＝ ver(真)＋ify(使……) → 核实；verdict ＝ ver(真)＋dict(说) → 裁决（说真话）；veritable ＝ verit(真)＋able → 名副其实的；veracity ＝ ver(真)＋acity → 诚实",
    "verb": "词源：拉丁语 verbum「词语」\n核心义：词语；言辞\n典型词：verbal ＝ verb(词)＋al → 言语的；verbose ＝ verb(词)＋ose(多……的) → 冗长的；proverb ＝ pro(公开)＋verb(话) → 谚语；verbatim ＝ verbatim(逐字) → 逐字地",
    "vers": "词源：拉丁语 vertere「转」\n核心义：转；转变；诗句\n典型词：version ＝ vers(转)＋ion → 版本（转译之物）；reverse ＝ re(回)＋verse(转) → 逆转；universe ＝ uni(一)＋verse(转) → 宇宙（万物旋转为一体）；diverse ＝ di(分开)＋verse(转) → 多样的；versatile ＝ vers(转)＋atile → 多才多艺的",
    "vert": "词源：拉丁语 vertere「转」\n核心义：转；翻转\n典型词：convert ＝ con(完全)＋vert(转) → 转变；divert ＝ di(分开)＋vert(转) → 转移；introvert ＝ intro(向内)＋vert(转) → 内向者；advertisement ＝ ad(去)＋vert(转→吸引注意)＋isement → 广告",
    "vest": "词源：拉丁语 vestire「穿衣」/vestis「衣服」\n核心义：衣服；穿衣；赋予\n典型词：vest ＝ vest(衣) → 背心；invest ＝ in(入)＋vest(衣→穿上官服) → 投资、授予；divest ＝ di(去除)＋vest(衣) → 剥夺（脱衣）；vestment ＝ vest(衣)＋ment → 法衣、礼服",
    "vict": "词源：拉丁语 vincere「征服」的分词词干\n核心义：征服；胜利\n典型词：victory ＝ vict(胜)＋ory → 胜利；victorious ＝ victori(胜)＋ous → 获胜的；convict ＝ con(完全)＋vict(征服) → 定罪（彻底制服）；evict ＝ e(出)＋vict(驱) → 逐出",
    "vid": "词源：拉丁语 videre「看」\n核心义：看；看见\n典型词：video ＝ vid(看)＋eo → 视频；evident ＝ e(出)＋vid(看)＋ent → 明显的（看得出的）；provide ＝ pro(预先)＋vide(看→预见而备) → 提供；prudent ＝ pro(前)＋udent(=vident 看) → 谨慎的",
    "vigil": "词源：拉丁语 vigil「清醒的、警觉的」\n核心义：清醒；警戒；守夜\n典型词：vigilant ＝ vigil(警觉)＋ant → 警惕的；vigil ＝ vigil(守夜) → 守夜、监视；invigilate ＝ in(内)＋vigil(监视)＋ate → 监考；reveille ＝ re＋veille(唤醒) → 起床号",
    "vinc": "词源：拉丁语 vincere「征服、战胜」\n核心义：征服；战胜\n典型词：convince ＝ con(完全)＋vince(征服) → 使确信（彻底说服）；invincible ＝ in(不)＋vinc(胜)＋ible → 不可战胜的；vincible ＝ vinc(胜)＋ible → 可征服的；province ＝ pro(前)＋vince(征服→管辖) → 省份",
    "viol": "词源：拉丁语 vis「力量」/violare「使用暴力」\n核心义：力量；暴力；违反\n典型词：violence ＝ viol(暴力)＋ence → 暴力；violent ＝ viol(暴)＋ent → 暴力的；violate ＝ viol(暴力→侵犯)＋ate → 违反；violation ＝ viol(侵)＋ation → 违反行为",
    "vis": "词源：拉丁语 videre「看」的词干\n核心义：看；视觉；景象\n典型词：visible ＝ vis(看)＋ible(可……的) → 可见的；vision ＝ vis(视)＋ion → 视力、愿景；visual ＝ vis(视)＋ual → 视觉的；revise ＝ re(再)＋vise(看) → 修订；supervise ＝ super(上)＋vise(看) → 监督",
    "vit": "词源：拉丁语 vita「生命」\n核心义：生命；活力\n典型词：vital ＝ vit(生命)＋al → 至关重要的；vitality ＝ vit(生命)＋ality → 活力；vitamin ＝ vit(生命)＋amin(胺) → 维生素；vital signs → 生命体征",
    "viv": "词源：拉丁语 vivere「活着」\n核心义：活；生存；生动\n典型词：survive ＝ sur(超过)＋vive(活) → 幸存；vivid ＝ viv(活)＋id → 生动的；revive ＝ re(再)＋vive(活) → 复苏；vivacious ＝ viv(活)＋acious → 活泼的",
    "voc": "词源：拉丁语 vox/vocis「声音」\n核心义：声音；喊叫；称呼\n典型词：vocal ＝ voc(声)＋al → 声音的；advocate ＝ ad(去)＋voc(喊→呼吁)＋ate → 提倡者；vocabulary ＝ vocabul(称呼→词)＋ary → 词汇表；provoke ＝ pro(前)＋voke(喊) → 激怒；equivocal ＝ equi(相等→模棱)＋voc(称)＋al → 模棱两可的",
    "vol": "词源：拉丁语 velle「意愿」（voluntas「意志」）\n核心义：意愿；意志\n典型词：volunteer ＝ volunt(意愿)＋eer → 志愿者；voluntary ＝ volunt(愿)＋ary → 自愿的；benevolent ＝ bene(善)＋vol(愿)＋ent → 仁慈的；malevolent ＝ male(恶)＋vol(愿)＋ent → 恶毒的",
    "volv": "词源：拉丁语 volvere「滚动、旋转」\n核心义：滚；转；卷\n典型词：involve ＝ in(入)＋volve(卷) → 涉及（卷入）；revolve ＝ re(回)＋volve(转) → 旋转；evolve ＝ e(出)＋volve(转→展开) → 演化；volume ＝ volu(卷)＋me → 卷、音量（书卷）；revolt ＝ re(回)＋volt(转) → 反叛",
    "vor": "词源：拉丁语 vorare「吞吃」\n核心义：吞吃；贪食\n典型词：voracious ＝ vor(吞)＋acious → 贪吃的；carnivore ＝ carni(肉)＋vore(吃) → 食肉动物；herbivore ＝ herbi(草)＋vore → 食草动物；devour ＝ de(完全)＋vour(吞) → 吞噬",
    "zoo": "词源：希腊语 zōion「动物」\n核心义：动物\n典型词：zoo ＝ zoo(动物)＋(公园) → 动物园；zoology ＝ zoo(动物)＋logy(学) → 动物学；zodiac ＝ zo(动物)＋diac(圈) → 黄道带（动物之环）；protozoa ＝ proto(最初)＋zoa(动物) → 原生动物",
}


async def main() -> None:
    updated = missing = 0
    async with engine.begin() as conn:
        for root_text, desc in DETAILED_ROOTS.items():
            res = await conn.execute(
                text("UPDATE roots SET description = :d WHERE text = :t"),
                {"d": desc, "t": root_text},
            )
            if res.rowcount and res.rowcount > 0:
                updated += 1
            else:
                missing += 1
                print(f"WARN: root not found in DB: {root_text}")
    await engine.dispose()
    print(f"Enriched {updated} roots ({missing} missing).")


if __name__ == "__main__":
    asyncio.run(main())
